/**
 * KemdiCode MCP Server
 * Copyright (C) 2025-2026 Kemdi Sp. z o.o. (Dawid Irzyk <dawid@kemdi.pl>)
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 */

/**
 * Audit Schedule Store
 *
 * Redis-based persistence for recurring audit schedules.
 * Each schedule defines a periodic magistrale dispatch with
 * optional self-assessment and kanban feedback loop.
 *
 * @module cluster-bus/audit-schedule-store
 */

import { v4 as uuidv4 } from 'uuid';
import { Logger } from '../utils/logger.js';
import { getSharedRedis } from '../infrastructure/redis/connection.js';

// ---------------------------------------------------------------------------
// Keys
// ---------------------------------------------------------------------------

const AUDIT_KEYS = {
  /** Set of all schedule IDs */
  schedules: 'mcp:audit:schedules',
  /** Hash: schedule config */
  schedule: (id: string) => `mcp:audit:schedule:${id}`,
  /** List: execution history (capped) */
  history: (id: string) => `mcp:audit:history:${id}`,
  /** String: ISO timestamp of last run */
  lastRun: (id: string) => `mcp:audit:last-run:${id}`,
} as const;

const MAX_HISTORY_ENTRIES = 50;

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface AuditSchedule {
  id: string;
  name: string;
  /** Interval in milliseconds between audit runs */
  intervalMs: number;
  /** Whether this schedule is active */
  enabled: boolean;
  /** Audit type label (e.g., "security", "performance", "full") */
  auditType: string;
  /** Base prompt for the magistrale dispatch */
  prompt: string;
  /** Focus areas for work partitioning across clusters */
  focusAreas: string[];
  /** Magistrale configuration */
  magistraleConfig: {
    maxTargets: number;
    timeoutMs: number;
    orchestrateAgent: 'plan' | 'build' | 'explore' | 'general';
    orchestrateMaxIterations: number;
    orchestrateMaxTokens: number;
    orchestrateEnableCognition: boolean;
    orchestrateEnableKanban: boolean;
    orchestrateEnableCollaboration: boolean;
  };
  /** Board ID for recording findings (optional) */
  boardId?: string;
  /** Enable self-assessment after audit to generate follow-up focus areas */
  selfAssessEnabled: boolean;
  /** Enable feedback loop: read kanban before audit to adjust focus */
  feedbackLoopEnabled: boolean;
  /** Created timestamp (ISO) */
  createdAt: string;
  /** Last updated timestamp (ISO) */
  updatedAt: string;
}

export interface AuditHistoryEntry {
  /** Execution timestamp (ISO) */
  timestamp: string;
  /** Duration in ms */
  durationMs: number;
  /** Number of clusters that responded */
  successCount: number;
  /** Number of clusters dispatched to */
  dispatchedTo: number;
  /** Focus areas used for this run */
  focusAreas: string[];
  /** Summary of findings (truncated) */
  summary: string;
  /** Follow-up focus areas generated by self-assessment */
  followUpAreas?: string[];
  /** Whether feedback loop was used */
  feedbackUsed: boolean;
}

export type CreateScheduleInput = Omit<AuditSchedule, 'id' | 'createdAt' | 'updatedAt'>;

// ---------------------------------------------------------------------------
// CRUD
// ---------------------------------------------------------------------------

export async function createSchedule(input: CreateScheduleInput): Promise<AuditSchedule> {
  const redis = await getSharedRedis();
  const id = uuidv4();
  const now = new Date().toISOString();

  const schedule: AuditSchedule = {
    id,
    ...input,
    createdAt: now,
    updatedAt: now,
  };

  await redis.hset(AUDIT_KEYS.schedule(id), 'data', JSON.stringify(schedule));
  await redis.sadd(AUDIT_KEYS.schedules, id);

  Logger.debug(`[AuditSchedule] Created schedule "${schedule.name}" (${id})`);
  return schedule;
}

export async function getSchedule(id: string): Promise<AuditSchedule | null> {
  const redis = await getSharedRedis();
  const raw = await redis.hget(AUDIT_KEYS.schedule(id), 'data');
  if (!raw) return null;
  return JSON.parse(raw) as AuditSchedule;
}

export async function updateSchedule(
  id: string,
  updates: Partial<Omit<AuditSchedule, 'id' | 'createdAt'>>
): Promise<AuditSchedule | null> {
  const existing = await getSchedule(id);
  if (!existing) return null;

  const updated: AuditSchedule = {
    ...existing,
    ...updates,
    id: existing.id,
    createdAt: existing.createdAt,
    updatedAt: new Date().toISOString(),
  };

  const redis = await getSharedRedis();
  await redis.hset(AUDIT_KEYS.schedule(id), 'data', JSON.stringify(updated));

  Logger.debug(`[AuditSchedule] Updated schedule "${updated.name}" (${id})`);
  return updated;
}

export async function deleteSchedule(id: string): Promise<boolean> {
  const redis = await getSharedRedis();
  const deleted = await redis.del(AUDIT_KEYS.schedule(id));
  await redis.srem(AUDIT_KEYS.schedules, id);
  await redis.del(AUDIT_KEYS.history(id));
  await redis.del(AUDIT_KEYS.lastRun(id));

  if (deleted > 0) {
    Logger.debug(`[AuditSchedule] Deleted schedule ${id}`);
  }
  return deleted > 0;
}

export async function listSchedules(): Promise<AuditSchedule[]> {
  const redis = await getSharedRedis();
  const ids = await redis.smembers(AUDIT_KEYS.schedules);
  if (ids.length === 0) return [];

  const pipeline = redis.pipeline();
  for (const id of ids) {
    pipeline.hget(AUDIT_KEYS.schedule(id), 'data');
  }
  const results = await pipeline.exec();

  const schedules: AuditSchedule[] = [];
  if (results) {
    for (const [err, raw] of results) {
      if (!err && raw && typeof raw === 'string') {
        schedules.push(JSON.parse(raw) as AuditSchedule);
      }
    }
  }

  return schedules;
}

// ---------------------------------------------------------------------------
// History
// ---------------------------------------------------------------------------

export async function addHistoryEntry(
  scheduleId: string,
  entry: AuditHistoryEntry
): Promise<void> {
  const redis = await getSharedRedis();
  const key = AUDIT_KEYS.history(scheduleId);

  await redis.lpush(key, JSON.stringify(entry));
  await redis.ltrim(key, 0, MAX_HISTORY_ENTRIES - 1);
  await redis.set(AUDIT_KEYS.lastRun(scheduleId), entry.timestamp);
}

export async function getHistory(
  scheduleId: string,
  limit = 10
): Promise<AuditHistoryEntry[]> {
  const redis = await getSharedRedis();
  const raw = await redis.lrange(AUDIT_KEYS.history(scheduleId), 0, limit - 1);
  return raw.map((r) => JSON.parse(r) as AuditHistoryEntry);
}

export async function getLastRunTime(scheduleId: string): Promise<string | null> {
  const redis = await getSharedRedis();
  return redis.get(AUDIT_KEYS.lastRun(scheduleId));
}
